<a href="https://colab.research.google.com/github/AyushPatil615/StockPriceAnalysisNPrediction/blob/main/Copy_of_Students_CNN_MNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, auc
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import mnist

# Load and preprocess MNIST dataset

In [2]:
(input_train, label_train), (input_test, label_test) = mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


# Reshape data to add channel dimension (28x28x1 for grayscale images)

In [3]:
input_train = input_train.reshape(input_train.shape[0], 28, 28, 1).astype('float32') / 255
input_test = input_test.reshape(input_test.shape[0], 28, 28, 1).astype('float32') / 255

# Convert labels to one-hot encoding

In [4]:
num_classes = 10
label_train_cat = to_categorical(label_train, num_classes)
label_test_cat = to_categorical(label_test, num_classes)

# Build CNN model

In [13]:
model = Sequential([
    Conv2D(32, kernel_size=(3,3), activation='relu', input_shape=(28,28,1)),
    MaxPooling2D(pool_size=(2,2)),
    Conv2D(64, kernel_size=(3,3), activation='relu'),
    MaxPooling2D(pool_size=(2,2)),
    Flatten(),
    Dense(128, activation='relu'),
    #Dropout(0.5),
    Dense(num_classes, activation='softmax')
])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


# Compile the model

In [14]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Display the model summary

In [15]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_10 (Conv2D)                   │ (None, 26, 26, 32)          │             320 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_10 (MaxPooling2D)      │ (None, 13, 13, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_11 (Conv2D)                   │ (None, 11, 11, 64)          │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_11 (MaxPooling2D)      │ (None, 5, 5, 64)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_4 (Flatten)                  │ (None, 1600)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_8 (Dense)                      │ (None, 128)                 │         204,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_9 (Dense)                      │ (None, 10)                  │           1,290 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 225,034 (879.04 KB)

 Trainable params: 225,034 (879.04 KB)

 Non-trainable params: 0 (0.00 B)

# Train the model

In [16]:
history = model.fit(input_train, label_train_cat, epochs=10, batch_size=128, validation_split=0.2)

Epoch 1/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 43s 110ms/step - accuracy: 0.8442 - loss: 0.5450 - val_accuracy: 0.9768 - val_loss: 0.0829
Epoch 2/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 78s 100ms/step - accuracy: 0.9791 - loss: 0.0690 - val_accuracy: 0.9848 - val_loss: 0.0557
Epoch 3/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 38s 101ms/step - accuracy: 0.9868 - loss: 0.0439 - val_accuracy: 0.9878 - val_loss: 0.0443
Epoch 4/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 41s 102ms/step - accuracy: 0.9899 - loss: 0.0329 - val_accuracy: 0.9880 - val_loss: 0.0418
Epoch 5/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 37s 99ms/step - accuracy: 0.9918 - loss: 0.0258 - val_accuracy: 0.9885 - val_loss: 0.0417
Epoch 6/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 44s 106ms/step - accuracy: 0.9934 - loss: 0.0209 - val_accuracy: 0.9878 - val_loss: 0.0416
Epoch 7/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 36s 97ms/step - accuracy: 0.9959 - loss: 0.0139 - val_accuracy: 0.9909 - val_loss: 0.0363
Epoch 8/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 40s 106ms/step - accuracy: 0.9962 - loss: 0.0

# Evaluate the model

In [17]:
test_loss, test_accuracy = model.evaluate(input_test, label_test_cat)
print(f"Test Loss: {test_loss:.4f}, Test Accuracy: {test_accuracy:.4f}")

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9869 - loss: 0.0441
Test Loss: 0.0396, Test Accuracy: 0.9888


# Predictions

In [18]:
predictions = model.predict(input_test)
predicted_classes = np.argmax(predictions, axis=1)

313/313 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step


# Confusion Matrix

In [20]:
conf_matrix = confusion_matrix(label_test, predicted_classes)
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[ 974    0    0    0    1    0    2    1    2    0]
 [   0 1115    0    2    2    0    6    0   10    0]
 [   0    0 1018    2    2    0    0    6    4    0]
 [   0    0    0 1008    0    1    0    0    1    0]
 [   0    0    0    0  981    0    1    0    0    0]
 [   0    0    0   12    0  876    2    0    0    2]
 [   1    1    0    0    2    2  950    0    2    0]
 [   0    2    3    5    0    0    0 1013    3    2]
 [   2    0    1    0    0    2    0    1  966    2]
 [   1    0    0    0    8    3    0    2    8  987]]


# Classification Report

In [21]:
report = classification_report(label_test, predicted_classes, target_names=[str(i) for i in range(10)])
print("\nClassification Report:")
print(report)


Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       980
           1       1.00      0.98      0.99      1135
           2       1.00      0.99      0.99      1032
           3       0.98      1.00      0.99      1010
           4       0.98      1.00      0.99       982
           5       0.99      0.98      0.99       892
           6       0.99      0.99      0.99       958
           7       0.99      0.99      0.99      1028
           8       0.97      0.99      0.98       974
           9       0.99      0.98      0.99      1009

    accuracy                           0.99     10000
   macro avg       0.99      0.99      0.99     10000
weighted avg       0.99      0.99      0.99     10000



# Sensitivity and Specificity (Per Class)

In [22]:
print("\nSensitivity and Specificity:")
for i in range(num_classes):
    TP = conf_matrix[i, i]
    FN = np.sum(conf_matrix[i, :]) - TP
    FP = np.sum(conf_matrix[:, i]) - TP
    TN = np.sum(conf_matrix) - (TP + FP + FN)
    sensitivity = TP / (TP + FN) if (TP + FN) > 0 else 0
    specificity = TN / (TN + FP) if (TN + FP) > 0 else 0
    print(f"Class {i}: Sensitivity = {sensitivity:.4f}, Specificity = {specificity:.4f}")


Sensitivity and Specificity:
Class 0: Sensitivity = 0.9939, Specificity = 0.9996
Class 1: Sensitivity = 0.9824, Specificity = 0.9997
Class 2: Sensitivity = 0.9864, Specificity = 0.9996
Class 3: Sensitivity = 0.9980, Specificity = 0.9977
Class 4: Sensitivity = 0.9990, Specificity = 0.9983
Class 5: Sensitivity = 0.9821, Specificity = 0.9991
Class 6: Sensitivity = 0.9916, Specificity = 0.9988
Class 7: Sensitivity = 0.9854, Specificity = 0.9989
Class 8: Sensitivity = 0.9918, Specificity = 0.9967
Class 9: Sensitivity = 0.9782, Specificity = 0.9993
